In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/processed/physics_dataset_v2.csv")

print(df.shape)

(1859, 8)

In [3]:
df[['teq_recalc', 'pl_rade']].describe()

        teq_recalc      pl_rade
count  1859.000000  1859.000000
mean    912.185928     6.525629
std     558.244011     5.871619
min       2.472050     0.370000
25%     521.376434     1.895000
50%     830.701309     3.080000
75%    1221.818440    12.470018
max    7851.798950    77.342100

In [7]:
df['habitable'] = (
    (df['teq_recalc'] >= 200) &
    (df['teq_recalc'] <= 350) &
    (df['pl_rade'] <= 1.6)
).astype(int)

df['habitable'].value_counts()
df['habitable'].value_counts(normalize=True)

habitable
0    0.994621
1    0.005379
Name: proportion, dtype: float64

In [8]:
df[df['habitable'] == 1][['teq_recalc', 'pl_rade']].describe()

       teq_recalc    pl_rade
count   10.000000  10.000000
mean   285.561606   1.115400
std     48.025602   0.326771
min    204.787254   0.637000
25%    250.219060   0.846000
50%    284.712660   1.133500
75%    326.565656   1.407500
max    347.648058   1.530000

In [9]:
df.to_csv("../data/processed/modeling_dataset_v1.csv", index=False)